package cse.duytan.coms.models;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Created by lehoangdung on 9/12/2017.
 */

public class BoardOfReview implements Serializable {

    @SerializedName("CONFERENCE_BOARD_OF_REVIEW_ID")
    public int CONFERENCE_BOARD_OF_REVIEW_ID;
    @SerializedName("CONFERENCE_ID")
    public int CONFERENCE_ID;
    @SerializedName("PAPER_ABSTRACT_REVIEW_DEADLINE_1")
    public String PAPER_ABSTRACT_REVIEW_DEADLINE_1;
    @SerializedName("PAPER_ABSTRACT_REVIEW_DEADLINE_2")
    public String PAPER_ABSTRACT_REVIEW_DEADLINE_2;
    @SerializedName("PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP")
    public int PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP;
    @SerializedName("PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT")
    public int PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT;
    @SerializedName("PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT")
    public int PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT;

    public BoardOfReview() {
    }

    public BoardOfReview(int CONFERENCE_BOARD_OF_REVIEW_ID, int CONFERENCE_ID, String PAPER_ABSTRACT_REVIEW_DEADLINE_1,
                         String PAPER_ABSTRACT_REVIEW_DEADLINE_2, int PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP,
                         int PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT, int PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT) {
        this.CONFERENCE_BOARD_OF_REVIEW_ID = CONFERENCE_BOARD_OF_REVIEW_ID;
        this.CONFERENCE_ID = CONFERENCE_ID;
        this.PAPER_ABSTRACT_REVIEW_DEADLINE_1 = PAPER_ABSTRACT_REVIEW_DEADLINE_1;
        this.PAPER_ABSTRACT_REVIEW_DEADLINE_2 = PAPER_ABSTRACT_REVIEW_DEADLINE_2;
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP = PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP;
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT = PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT;
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT = PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT;
    }

    public int getCONFERENCE_BOARD_OF_REVIEW_ID() {
        return CONFERENCE_BOARD_OF_REVIEW_ID;
    }

    public void setCONFERENCE_BOARD_OF_REVIEW_ID(int CONFERENCE_BOARD_OF_REVIEW_ID) {
        this.CONFERENCE_BOARD_OF_REVIEW_ID = CONFERENCE_BOARD_OF_REVIEW_ID;
    }

    public int getCONFERENCE_ID() {
        return CONFERENCE_ID;
    }

    public void setCONFERENCE_ID(int CONFERENCE_ID) {
        this.CONFERENCE_ID = CONFERENCE_ID;
    }

    public String getPAPER_ABSTRACT_REVIEW_DEADLINE_1() {
        return PAPER_ABSTRACT_REVIEW_DEADLINE_1;
    }

    public void setPAPER_ABSTRACT_REVIEW_DEADLINE_1(String PAPER_ABSTRACT_REVIEW_DEADLINE_1) {
        this.PAPER_ABSTRACT_REVIEW_DEADLINE_1 = PAPER_ABSTRACT_REVIEW_DEADLINE_1;
    }

    public String getPAPER_ABSTRACT_REVIEW_DEADLINE_2() {
        return PAPER_ABSTRACT_REVIEW_DEADLINE_2;
    }

    public void setPAPER_ABSTRACT_REVIEW_DEADLINE_2(String PAPER_ABSTRACT_REVIEW_DEADLINE_2) {
        this.PAPER_ABSTRACT_REVIEW_DEADLINE_2 = PAPER_ABSTRACT_REVIEW_DEADLINE_2;
    }

    public int getPAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP() {
        return PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP;
    }

    public void setPAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP(int PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP) {
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP = PAPER_ABSTRACT_REVIEW_RATING_SCALE_STEP;
    }

    public int getPAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT() {
        return PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT;
    }

    public void setPAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT(int PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT) {
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT = PAPER_ABSTRACT_REVIEW_RATING_SCALE_START_POINT;
    }

    public int getPAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT() {
        return PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT;
    }

    public void setPAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT(int PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT) {
        this.PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT = PAPER_ABSTRACT_REVIEW_RATING_SCALE_END_POINT;
    }
}
