package cse.duytan.coms.models;

import com.google.gson.annotations.SerializedName;

public class Package {

    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_ID")
    private int CONFERENCE_REGISTRATION_PACKAGE_ID;
    @SerializedName("CONFERENCE_ID")
    private int CONFERENCE_ID;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_NAME")
    private String CONFERENCE_REGISTRATION_PACKAGE_NAME;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_NAME_EN")
    private String CONFERENCE_REGISTRATION_PACKAGE_NAME_EN;
    @SerializedName("EFFECTIVE_FROM_DATE")
    private String EFFECTIVE_FROM_DATE;
    @SerializedName("EFFECTIVE_THRU_DATE")
    private String EFFECTIVE_THRU_DATE;
    @SerializedName("DESCRIPTION")
    private String DESCRIPTION;
    @SerializedName("DESCRIPTION_EN")
    private String DESCRIPTION_EN;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_PRICE")
    private int CONFERENCE_REGISTRATION_PACKAGE_PRICE;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME")
    private String CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10")
    private int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10;
    @SerializedName("CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10")
    private String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10;

    public Package() {
    }

    public Package(int CONFERENCE_REGISTRATION_PACKAGE_ID, int CONFERENCE_ID, String CONFERENCE_REGISTRATION_PACKAGE_NAME, String CONFERENCE_REGISTRATION_PACKAGE_NAME_EN, String EFFECTIVE_FROM_DATE, String EFFECTIVE_THRU_DATE, String DESCRIPTION, String DESCRIPTION_EN, int CONFERENCE_REGISTRATION_PACKAGE_PRICE, String CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10, int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10, String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_ID = CONFERENCE_REGISTRATION_PACKAGE_ID;
        this.CONFERENCE_ID = CONFERENCE_ID;
        this.CONFERENCE_REGISTRATION_PACKAGE_NAME = CONFERENCE_REGISTRATION_PACKAGE_NAME;
        this.CONFERENCE_REGISTRATION_PACKAGE_NAME_EN = CONFERENCE_REGISTRATION_PACKAGE_NAME_EN;
        this.EFFECTIVE_FROM_DATE = EFFECTIVE_FROM_DATE;
        this.EFFECTIVE_THRU_DATE = EFFECTIVE_THRU_DATE;
        this.DESCRIPTION = DESCRIPTION;
        this.DESCRIPTION_EN = DESCRIPTION_EN;
        this.CONFERENCE_REGISTRATION_PACKAGE_PRICE = CONFERENCE_REGISTRATION_PACKAGE_PRICE;
        this.CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME = CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10;
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_ID() {
        return CONFERENCE_REGISTRATION_PACKAGE_ID;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_ID(int CONFERENCE_REGISTRATION_PACKAGE_ID) {
        this.CONFERENCE_REGISTRATION_PACKAGE_ID = CONFERENCE_REGISTRATION_PACKAGE_ID;
    }

    public int getCONFERENCE_ID() {
        return CONFERENCE_ID;
    }

    public void setCONFERENCE_ID(int CONFERENCE_ID) {
        this.CONFERENCE_ID = CONFERENCE_ID;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_NAME() {
        return CONFERENCE_REGISTRATION_PACKAGE_NAME;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_NAME(String CONFERENCE_REGISTRATION_PACKAGE_NAME) {
        this.CONFERENCE_REGISTRATION_PACKAGE_NAME = CONFERENCE_REGISTRATION_PACKAGE_NAME;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_NAME_EN() {
        return CONFERENCE_REGISTRATION_PACKAGE_NAME_EN;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_NAME_EN(String CONFERENCE_REGISTRATION_PACKAGE_NAME_EN) {
        this.CONFERENCE_REGISTRATION_PACKAGE_NAME_EN = CONFERENCE_REGISTRATION_PACKAGE_NAME_EN;
    }

    public String getEFFECTIVE_FROM_DATE() {
        return EFFECTIVE_FROM_DATE;
    }

    public void setEFFECTIVE_FROM_DATE(String EFFECTIVE_FROM_DATE) {
        this.EFFECTIVE_FROM_DATE = EFFECTIVE_FROM_DATE;
    }

    public String getEFFECTIVE_THRU_DATE() {
        return EFFECTIVE_THRU_DATE;
    }

    public void setEFFECTIVE_THRU_DATE(String EFFECTIVE_THRU_DATE) {
        this.EFFECTIVE_THRU_DATE = EFFECTIVE_THRU_DATE;
    }

    public String getDESCRIPTION() {
        return DESCRIPTION;
    }

    public void setDESCRIPTION(String DESCRIPTION) {
        this.DESCRIPTION = DESCRIPTION;
    }

    public String getDESCRIPTION_EN() {
        return DESCRIPTION_EN;
    }

    public void setDESCRIPTION_EN(String DESCRIPTION_EN) {
        this.DESCRIPTION_EN = DESCRIPTION_EN;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_PRICE() {
        return CONFERENCE_REGISTRATION_PACKAGE_PRICE;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_PRICE(int CONFERENCE_REGISTRATION_PACKAGE_PRICE) {
        this.CONFERENCE_REGISTRATION_PACKAGE_PRICE = CONFERENCE_REGISTRATION_PACKAGE_PRICE;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME() {
        return CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME(String CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME) {
        this.CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME = CONFERENCE_REGISTRATION_PACKAGE_PRICE_CURRENCY_UOM_NAME;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_1;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_1;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_1;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_1;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_1;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_1;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_1;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_2;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_2;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_2;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_2;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_2;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_2;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_2;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_3;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_3;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_3;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_3;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_3;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_3;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_3;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_4;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_4;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_4;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_4;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_4;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_4;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_4;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_5;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_5;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_5;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_5;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_5;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_5;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_5;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_6;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_6;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_6;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_6;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_6;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_6;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_6;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_7;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_7;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_7;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_7;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_7;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_7;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_7;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_8;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_8;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_8;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_8;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_8;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_8;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_8;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_9;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_9;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_9;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_9;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_9;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_9;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_9;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_ID_10;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_10;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_NAME_EN_10;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_10;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_DESCRIPTION_EN_10;
    }

    public int getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10(int CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_10;
    }

    public String getCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10() {
        return CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10;
    }

    public void setCONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10(String CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10) {
        this.CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10 = CONFERENCE_REGISTRATION_PACKAGE_OFFERING_VALUE_CURRENCY_UOM_NAME_10;
    }
}