package cse.duytan.coms.models;

import com.google.gson.annotations.SerializedName;

/**
 * Created by iMac on 8/21/17.
 */

public class PaperAbstract {
    @SerializedName("PAPER_ID")
    public int PAPER_ID;
    @SerializedName("PAPER_NUMBER_OR_CODE")
    public String PAPER_NUMBER_OR_CODE;
    @SerializedName("PAPER_ABSTRACT_TITLE_1")
    public String PAPER_ABSTRACT_TITLE_1;
    @SerializedName("PAPER_ABSTRACT_TITLE_EN_1")
    public String PAPER_ABSTRACT_TITLE_EN_1;
    @SerializedName("CONFERENCE_SESSION_TOPIC_ID_1")
    public int CONFERENCE_SESSION_TOPIC_ID_1;
    @SerializedName("CONFERENCE_SESSION_TOPIC_NAME_1")
    public String CONFERENCE_SESSION_TOPIC_NAME_1;
    @SerializedName("CONFERENCE_SESSION_TOPIC_NAME_EN_1")
    public String CONFERENCE_SESSION_TOPIC_NAME_EN_1;
    @SerializedName("PAPER_ABSTRACT_TEXT_1")
    public String PAPER_ABSTRACT_TEXT_1;
    @SerializedName("PAPER_ABSTRACT_TEXT_EN_1")
    public String PAPER_ABSTRACT_TEXT_EN_1;
    @SerializedName("PAPER_ABSTRACT_ATTACHED_FILENAME_1")
    public String PAPER_ABSTRACT_ATTACHED_FILENAME_1;
    @SerializedName("WORD_COUNT_OF_PAPER_ABSTRACT_1")
    public String WORD_COUNT_OF_PAPER_ABSTRACT_1;
    @SerializedName("KEYWORDS_1")
    public String KEYWORDS_1;
    @SerializedName("FULL_PAPER_OR_WORK_IN_PROGRESS_1")
    public String FULL_PAPER_OR_WORK_IN_PROGRESS_1;
    @SerializedName("TYPE_OF_STUDY_ID_1")
    public String TYPE_OF_STUDY_ID_1;
    @SerializedName("TYPE_OF_STUDY_NAME_1")
    public String TYPE_OF_STUDY_NAME_1;
    @SerializedName("TYPE_OF_STUDY_NAME_EN_1")
    public String TYPE_OF_STUDY_NAME_EN_1;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID_1")
    public String CONFERENCE_PRESENTATION_TYPE_ID_1;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_1")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_1;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN_1")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN_1;
    @SerializedName("FIRST_SUBMITTED_DATE_1")
    public String FIRST_SUBMITTED_DATE_1;
    @SerializedName("LAST_REVISED_DATE_1")
    public String LAST_REVISED_DATE_1;
    @SerializedName("PAPER_ABSTRACT_TITLE_2")
    public String PAPER_ABSTRACT_TITLE_2;
    @SerializedName("PAPER_ABSTRACT_TITLE_EN_2")
    public String PAPER_ABSTRACT_TITLE_EN_2;
    @SerializedName("CONFERENCE_SESSION_TOPIC_ID_2")
    public String CONFERENCE_SESSION_TOPIC_ID_2;
    @SerializedName("CONFERENCE_SESSION_TOPIC_NAME_2")
    public String CONFERENCE_SESSION_TOPIC_NAME_2;
    @SerializedName("CONFERENCE_SESSION_TOPIC_NAME_EN_2")
    public String CONFERENCE_SESSION_TOPIC_NAME_EN_2;
    @SerializedName("PAPER_ABSTRACT_TEXT_2")
    public String PAPER_ABSTRACT_TEXT_2;
    @SerializedName("PAPER_ABSTRACT_TEXT_EN_2")
    public String PAPER_ABSTRACT_TEXT_EN_2;
    @SerializedName("PAPER_ABSTRACT_ATTACHED_FILENAME_2")
    public String PAPER_ABSTRACT_ATTACHED_FILENAME_2;
    @SerializedName("WORD_COUNT_OF_PAPER_ABSTRACT_2")
    public String WORD_COUNT_OF_PAPER_ABSTRACT_2;
    @SerializedName("KEYWORDS_2")
    public String KEYWORDS_2;
    @SerializedName("FULL_PAPER_OR_WORK_IN_PROGRESS_2")
    public String FULL_PAPER_OR_WORK_IN_PROGRESS_2;
    @SerializedName("TYPE_OF_STUDY_ID_2")
    public String TYPE_OF_STUDY_ID_2;
    @SerializedName("TYPE_OF_STUDY_NAME_2")
    public String TYPE_OF_STUDY_NAME_2;
    @SerializedName("TYPE_OF_STUDY_NAME_EN_2")
    public String TYPE_OF_STUDY_NAME_EN_2;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID_2")
    public String CONFERENCE_PRESENTATION_TYPE_ID_2;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_2")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_2;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN_2")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN_2;
    @SerializedName("FIRST_SUBMITTED_DATE_2")
    public String FIRST_SUBMITTED_DATE_2;
    @SerializedName("LAST_REVISED_DATE_2")
    public String LAST_REVISED_DATE_2;
    @SerializedName("LAST_REVISED_DATE_3")
    public String LAST_REVISED_DATE_3;
    @SerializedName("PAPER_ABSTRACT_TEXT_3")
    public String PAPER_ABSTRACT_TEXT_3;
    @SerializedName("PAPER_ABSTRACT_TEXT_EN_3")
    public String PAPER_ABSTRACT_TEXT_EN_3;
    @SerializedName("PAPER_ABSTRACT_ATTACHED_FILENAME_3")
    public String PAPER_ABSTRACT_ATTACHED_FILENAME_3;
    @SerializedName("WORD_COUNT_OF_PAPER_ABSTRACT_3")
    public String WORD_COUNT_OF_PAPER_ABSTRACT_3;
    @SerializedName("KEYWORDS_3")
    public String KEYWORDS_3;
    @SerializedName("FULL_PAPER_OR_WORK_IN_PROGRESS_3")
    public String FULL_PAPER_OR_WORK_IN_PROGRESS_3;
    @SerializedName("TYPE_OF_STUDY_ID_3")
    public String TYPE_OF_STUDY_ID_3;
    @SerializedName("TYPE_OF_STUDY_NAME_3")
    public String TYPE_OF_STUDY_NAME_3;
    @SerializedName("TYPE_OF_STUDY_NAME_EN_3")
    public String TYPE_OF_STUDY_NAME_EN_3;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID_3")
    public String CONFERENCE_PRESENTATION_TYPE_ID_3;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_3")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_3;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN_3")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN_3;
    @SerializedName("FIRST_SUBMITTED_DATE_3")
    public String FIRST_SUBMITTED_DATE_3;
    @SerializedName("LAST_REVISED_DATE_4")
    public String LAST_REVISED_DATE_4;
    @SerializedName("PAPER_ABSTRACT_TEXT_4")
    public String PAPER_ABSTRACT_TEXT_4;
    @SerializedName("PAPER_ABSTRACT_TEXT_EN_4")
    public String PAPER_ABSTRACT_TEXT_EN_4;
    @SerializedName("PAPER_ABSTRACT_ATTACHED_FILENAME_4")
    public String PAPER_ABSTRACT_ATTACHED_FILENAME_4;
    @SerializedName("WORD_COUNT_OF_PAPER_ABSTRACT_4")
    public String WORD_COUNT_OF_PAPER_ABSTRACT_4;
    @SerializedName("KEYWORDS_4")
    public String KEYWORDS_4;
    @SerializedName("FULL_PAPER_OR_WORK_IN_PROGRESS_4")
    public String FULL_PAPER_OR_WORK_IN_PROGRESS_4;
    @SerializedName("TYPE_OF_STUDY_ID_4")
    public String TYPE_OF_STUDY_ID_4;
    @SerializedName("TYPE_OF_STUDY_NAME_4")
    public String TYPE_OF_STUDY_NAME_4;
    @SerializedName("TYPE_OF_STUDY_NAME_EN_4")
    public String TYPE_OF_STUDY_NAME_EN_4;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID_4")
    public String CONFERENCE_PRESENTATION_TYPE_ID_4;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_4")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_4;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN_4")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN_4;
    @SerializedName("FIRST_SUBMITTED_DATE_4")
    public String FIRST_SUBMITTED_DATE_4;
    @SerializedName("LAST_REVISED_DATE_5")
    public String LAST_REVISED_DATE_5;
    @SerializedName("PAPER_ABSTRACT_TEXT_5")
    public String PAPER_ABSTRACT_TEXT_5;
    @SerializedName("PAPER_ABSTRACT_TEXT_EN_5")
    public String PAPER_ABSTRACT_TEXT_EN_5;
    @SerializedName("PAPER_ABSTRACT_ATTACHED_FILENAME_5")
    public String PAPER_ABSTRACT_ATTACHED_FILENAME_5;
    @SerializedName("WORD_COUNT_OF_PAPER_ABSTRACT_5")
    public String WORD_COUNT_OF_PAPER_ABSTRACT_5;
    @SerializedName("KEYWORDS_5")
    public String KEYWORDS_5;
    @SerializedName("FULL_PAPER_OR_WORK_IN_PROGRESS_5")
    public String FULL_PAPER_OR_WORK_IN_PROGRESS_5;
    @SerializedName("TYPE_OF_STUDY_ID_5")
    public String TYPE_OF_STUDY_ID_5;
    @SerializedName("TYPE_OF_STUDY_NAME_5")
    public String TYPE_OF_STUDY_NAME_5;
    @SerializedName("TYPE_OF_STUDY_NAME_EN_5")
    public String TYPE_OF_STUDY_NAME_EN_5;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID_5")
    public String CONFERENCE_PRESENTATION_TYPE_ID_5;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_5")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_5;
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN_5")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN_5;
    @SerializedName("FIRST_SUBMITTED_DATE_5")
    public String FIRST_SUBMITTED_DATE_5;
    @SerializedName("PAPER_ABSTRACT_WITHDRAWN")
    public String PAPER_ABSTRACT_WITHDRAWN;
    @SerializedName("PAPER_ABSTRACT_WITHDRAWN_SCRIPT")
    public String PAPER_ABSTRACT_WITHDRAWN_SCRIPT;
    @SerializedName("PAPER_ABSTRACT_WITHDRAWN_DATE")
    public String PAPER_ABSTRACT_WITHDRAWN_DATE;
    @SerializedName("PAPER_ABSTRACT_WITHDRAWN_NOTE")
    public String PAPER_ABSTRACT_WITHDRAWN_NOTE;
    @SerializedName("FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT")
    public String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT;
    @SerializedName("FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT")
    public String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT;
    @SerializedName("FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE")
    public String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE;
    @SerializedName("FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID")
    public String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID;
    @SerializedName("ASSIGNED_CONFERENCE_SESSION_TOPIC_ID")
    public int ASSIGNED_CONFERENCE_SESSION_TOPIC_ID;
    @SerializedName("ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME")
    public String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME;
    @SerializedName("ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN")
    public String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN;
    @SerializedName("PERSON_ID")
    public int PERSON_ID;
    @SerializedName("CURRENT_LAST_NAME")
    public String CURRENT_LAST_NAME;
    @SerializedName("CURRENT_MIDDLE_NAME")
    public String CURRENT_MIDDLE_NAME;
    @SerializedName("CURRENT_FIRST_NAME")
    public String CURRENT_FIRST_NAME;

    public PaperAbstract() {
    }

    public PaperAbstract(int PAPER_ID, String PAPER_NUMBER_OR_CODE, String PAPER_ABSTRACT_TITLE_1, String PAPER_ABSTRACT_TITLE_EN_1, int CONFERENCE_SESSION_TOPIC_ID_1, String CONFERENCE_SESSION_TOPIC_NAME_1, String CONFERENCE_SESSION_TOPIC_NAME_EN_1, String PAPER_ABSTRACT_TEXT_1, String PAPER_ABSTRACT_TEXT_EN_1, String PAPER_ABSTRACT_ATTACHED_FILENAME_1, String WORD_COUNT_OF_PAPER_ABSTRACT_1, String KEYWORDS_1, String FULL_PAPER_OR_WORK_IN_PROGRESS_1, String TYPE_OF_STUDY_ID_1, String TYPE_OF_STUDY_NAME_1, String TYPE_OF_STUDY_NAME_EN_1, String CONFERENCE_PRESENTATION_TYPE_ID_1, String CONFERENCE_PRESENTATION_TYPE_NAME_1, String CONFERENCE_PRESENTATION_TYPE_NAME_EN_1, String FIRST_SUBMITTED_DATE_1, String LAST_REVISED_DATE_1, String PAPER_ABSTRACT_TITLE_2, String PAPER_ABSTRACT_TITLE_EN_2, String CONFERENCE_SESSION_TOPIC_ID_2, String CONFERENCE_SESSION_TOPIC_NAME_2, String CONFERENCE_SESSION_TOPIC_NAME_EN_2, String PAPER_ABSTRACT_TEXT_2, String PAPER_ABSTRACT_TEXT_EN_2, String PAPER_ABSTRACT_ATTACHED_FILENAME_2, String WORD_COUNT_OF_PAPER_ABSTRACT_2, String KEYWORDS_2, String FULL_PAPER_OR_WORK_IN_PROGRESS_2, String TYPE_OF_STUDY_ID_2, String TYPE_OF_STUDY_NAME_2, String TYPE_OF_STUDY_NAME_EN_2, String CONFERENCE_PRESENTATION_TYPE_ID_2, String CONFERENCE_PRESENTATION_TYPE_NAME_2, String CONFERENCE_PRESENTATION_TYPE_NAME_EN_2, String FIRST_SUBMITTED_DATE_2, String LAST_REVISED_DATE_2, String LAST_REVISED_DATE_3, String PAPER_ABSTRACT_TEXT_3, String PAPER_ABSTRACT_TEXT_EN_3, String PAPER_ABSTRACT_ATTACHED_FILENAME_3, String WORD_COUNT_OF_PAPER_ABSTRACT_3, String KEYWORDS_3, String FULL_PAPER_OR_WORK_IN_PROGRESS_3, String TYPE_OF_STUDY_ID_3, String TYPE_OF_STUDY_NAME_3, String TYPE_OF_STUDY_NAME_EN_3, String CONFERENCE_PRESENTATION_TYPE_ID_3, String CONFERENCE_PRESENTATION_TYPE_NAME_3, String CONFERENCE_PRESENTATION_TYPE_NAME_EN_3, String FIRST_SUBMITTED_DATE_3, String LAST_REVISED_DATE_4, String PAPER_ABSTRACT_TEXT_4, String PAPER_ABSTRACT_TEXT_EN_4, String PAPER_ABSTRACT_ATTACHED_FILENAME_4, String WORD_COUNT_OF_PAPER_ABSTRACT_4, String KEYWORDS_4, String FULL_PAPER_OR_WORK_IN_PROGRESS_4, String TYPE_OF_STUDY_ID_4, String TYPE_OF_STUDY_NAME_4, String TYPE_OF_STUDY_NAME_EN_4, String CONFERENCE_PRESENTATION_TYPE_ID_4, String CONFERENCE_PRESENTATION_TYPE_NAME_4, String CONFERENCE_PRESENTATION_TYPE_NAME_EN_4, String FIRST_SUBMITTED_DATE_4, String LAST_REVISED_DATE_5, String PAPER_ABSTRACT_TEXT_5, String PAPER_ABSTRACT_TEXT_EN_5, String PAPER_ABSTRACT_ATTACHED_FILENAME_5, String WORD_COUNT_OF_PAPER_ABSTRACT_5, String KEYWORDS_5, String FULL_PAPER_OR_WORK_IN_PROGRESS_5, String TYPE_OF_STUDY_ID_5, String TYPE_OF_STUDY_NAME_5, String TYPE_OF_STUDY_NAME_EN_5, String CONFERENCE_PRESENTATION_TYPE_ID_5, String CONFERENCE_PRESENTATION_TYPE_NAME_5, String CONFERENCE_PRESENTATION_TYPE_NAME_EN_5, String FIRST_SUBMITTED_DATE_5, String PAPER_ABSTRACT_WITHDRAWN, String PAPER_ABSTRACT_WITHDRAWN_SCRIPT, String PAPER_ABSTRACT_WITHDRAWN_DATE, String PAPER_ABSTRACT_WITHDRAWN_NOTE, String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT, String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT, String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE, String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID, int ASSIGNED_CONFERENCE_SESSION_TOPIC_ID, String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME, String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN, int PERSON_ID, String CURRENT_LAST_NAME, String CURRENT_MIDDLE_NAME, String CURRENT_FIRST_NAME) {
        this.PAPER_ID = PAPER_ID;
        this.PAPER_NUMBER_OR_CODE = PAPER_NUMBER_OR_CODE;
        this.PAPER_ABSTRACT_TITLE_1 = PAPER_ABSTRACT_TITLE_1;
        this.PAPER_ABSTRACT_TITLE_EN_1 = PAPER_ABSTRACT_TITLE_EN_1;
        this.CONFERENCE_SESSION_TOPIC_ID_1 = CONFERENCE_SESSION_TOPIC_ID_1;
        this.CONFERENCE_SESSION_TOPIC_NAME_1 = CONFERENCE_SESSION_TOPIC_NAME_1;
        this.CONFERENCE_SESSION_TOPIC_NAME_EN_1 = CONFERENCE_SESSION_TOPIC_NAME_EN_1;
        this.PAPER_ABSTRACT_TEXT_1 = PAPER_ABSTRACT_TEXT_1;
        this.PAPER_ABSTRACT_TEXT_EN_1 = PAPER_ABSTRACT_TEXT_EN_1;
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_1 = PAPER_ABSTRACT_ATTACHED_FILENAME_1;
        this.WORD_COUNT_OF_PAPER_ABSTRACT_1 = WORD_COUNT_OF_PAPER_ABSTRACT_1;
        this.KEYWORDS_1 = KEYWORDS_1;
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_1 = FULL_PAPER_OR_WORK_IN_PROGRESS_1;
        this.TYPE_OF_STUDY_ID_1 = TYPE_OF_STUDY_ID_1;
        this.TYPE_OF_STUDY_NAME_1 = TYPE_OF_STUDY_NAME_1;
        this.TYPE_OF_STUDY_NAME_EN_1 = TYPE_OF_STUDY_NAME_EN_1;
        this.CONFERENCE_PRESENTATION_TYPE_ID_1 = CONFERENCE_PRESENTATION_TYPE_ID_1;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_1 = CONFERENCE_PRESENTATION_TYPE_NAME_1;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_1 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_1;
        this.FIRST_SUBMITTED_DATE_1 = FIRST_SUBMITTED_DATE_1;
        this.LAST_REVISED_DATE_1 = LAST_REVISED_DATE_1;
        this.PAPER_ABSTRACT_TITLE_2 = PAPER_ABSTRACT_TITLE_2;
        this.PAPER_ABSTRACT_TITLE_EN_2 = PAPER_ABSTRACT_TITLE_EN_2;
        this.CONFERENCE_SESSION_TOPIC_ID_2 = CONFERENCE_SESSION_TOPIC_ID_2;
        this.CONFERENCE_SESSION_TOPIC_NAME_2 = CONFERENCE_SESSION_TOPIC_NAME_2;
        this.CONFERENCE_SESSION_TOPIC_NAME_EN_2 = CONFERENCE_SESSION_TOPIC_NAME_EN_2;
        this.PAPER_ABSTRACT_TEXT_2 = PAPER_ABSTRACT_TEXT_2;
        this.PAPER_ABSTRACT_TEXT_EN_2 = PAPER_ABSTRACT_TEXT_EN_2;
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_2 = PAPER_ABSTRACT_ATTACHED_FILENAME_2;
        this.WORD_COUNT_OF_PAPER_ABSTRACT_2 = WORD_COUNT_OF_PAPER_ABSTRACT_2;
        this.KEYWORDS_2 = KEYWORDS_2;
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_2 = FULL_PAPER_OR_WORK_IN_PROGRESS_2;
        this.TYPE_OF_STUDY_ID_2 = TYPE_OF_STUDY_ID_2;
        this.TYPE_OF_STUDY_NAME_2 = TYPE_OF_STUDY_NAME_2;
        this.TYPE_OF_STUDY_NAME_EN_2 = TYPE_OF_STUDY_NAME_EN_2;
        this.CONFERENCE_PRESENTATION_TYPE_ID_2 = CONFERENCE_PRESENTATION_TYPE_ID_2;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_2 = CONFERENCE_PRESENTATION_TYPE_NAME_2;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_2 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_2;
        this.FIRST_SUBMITTED_DATE_2 = FIRST_SUBMITTED_DATE_2;
        this.LAST_REVISED_DATE_2 = LAST_REVISED_DATE_2;

        this.LAST_REVISED_DATE_3 = LAST_REVISED_DATE_3;
        this.PAPER_ABSTRACT_TEXT_3 = PAPER_ABSTRACT_TEXT_3;
        this.PAPER_ABSTRACT_TEXT_EN_3 = PAPER_ABSTRACT_TEXT_EN_3;
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_3 = PAPER_ABSTRACT_ATTACHED_FILENAME_3;
        this.WORD_COUNT_OF_PAPER_ABSTRACT_3 = WORD_COUNT_OF_PAPER_ABSTRACT_3;
        this.KEYWORDS_3 = KEYWORDS_3;
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_3 = FULL_PAPER_OR_WORK_IN_PROGRESS_3;
        this.TYPE_OF_STUDY_ID_3 = TYPE_OF_STUDY_ID_3;
        this.TYPE_OF_STUDY_NAME_3 = TYPE_OF_STUDY_NAME_3;
        this.TYPE_OF_STUDY_NAME_EN_3 = TYPE_OF_STUDY_NAME_EN_3;
        this.CONFERENCE_PRESENTATION_TYPE_ID_3 = CONFERENCE_PRESENTATION_TYPE_ID_3;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_3 = CONFERENCE_PRESENTATION_TYPE_NAME_3;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_3 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_3;
        this.FIRST_SUBMITTED_DATE_3 = FIRST_SUBMITTED_DATE_3;

        this.LAST_REVISED_DATE_4 = LAST_REVISED_DATE_4;
        this.PAPER_ABSTRACT_TEXT_4 = PAPER_ABSTRACT_TEXT_4;
        this.PAPER_ABSTRACT_TEXT_EN_4 = PAPER_ABSTRACT_TEXT_EN_4;
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_4 = PAPER_ABSTRACT_ATTACHED_FILENAME_4;
        this.WORD_COUNT_OF_PAPER_ABSTRACT_4 = WORD_COUNT_OF_PAPER_ABSTRACT_4;
        this.KEYWORDS_4 = KEYWORDS_4;
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_4 = FULL_PAPER_OR_WORK_IN_PROGRESS_4;
        this.TYPE_OF_STUDY_ID_4 = TYPE_OF_STUDY_ID_4;
        this.TYPE_OF_STUDY_NAME_4 = TYPE_OF_STUDY_NAME_4;
        this.TYPE_OF_STUDY_NAME_EN_4 = TYPE_OF_STUDY_NAME_EN_4;
        this.CONFERENCE_PRESENTATION_TYPE_ID_4 = CONFERENCE_PRESENTATION_TYPE_ID_4;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_4 = CONFERENCE_PRESENTATION_TYPE_NAME_4;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_4 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_4;
        this.FIRST_SUBMITTED_DATE_4 = FIRST_SUBMITTED_DATE_4;
        this.LAST_REVISED_DATE_5 = LAST_REVISED_DATE_5;
        this.PAPER_ABSTRACT_TEXT_5 = PAPER_ABSTRACT_TEXT_5;
        this.PAPER_ABSTRACT_TEXT_EN_5 = PAPER_ABSTRACT_TEXT_EN_5;
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_5 = PAPER_ABSTRACT_ATTACHED_FILENAME_5;
        this.WORD_COUNT_OF_PAPER_ABSTRACT_5 = WORD_COUNT_OF_PAPER_ABSTRACT_5;
        this.KEYWORDS_5 = KEYWORDS_5;
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_5 = FULL_PAPER_OR_WORK_IN_PROGRESS_5;
        this.TYPE_OF_STUDY_ID_5 = TYPE_OF_STUDY_ID_5;
        this.TYPE_OF_STUDY_NAME_5 = TYPE_OF_STUDY_NAME_5;
        this.TYPE_OF_STUDY_NAME_EN_5 = TYPE_OF_STUDY_NAME_EN_5;
        this.CONFERENCE_PRESENTATION_TYPE_ID_5 = CONFERENCE_PRESENTATION_TYPE_ID_5;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_5 = CONFERENCE_PRESENTATION_TYPE_NAME_5;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_5 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_5;
        this.FIRST_SUBMITTED_DATE_5 = FIRST_SUBMITTED_DATE_5;
        this.PAPER_ABSTRACT_WITHDRAWN = PAPER_ABSTRACT_WITHDRAWN;
        this.PAPER_ABSTRACT_WITHDRAWN_SCRIPT = PAPER_ABSTRACT_WITHDRAWN_SCRIPT;
        this.PAPER_ABSTRACT_WITHDRAWN_DATE = PAPER_ABSTRACT_WITHDRAWN_DATE;
        this.PAPER_ABSTRACT_WITHDRAWN_NOTE = PAPER_ABSTRACT_WITHDRAWN_NOTE;
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT;
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT;
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE;
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID;
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_ID = ASSIGNED_CONFERENCE_SESSION_TOPIC_ID;
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME = ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME;
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN = ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN;
        this.PERSON_ID = PERSON_ID;
        this.CURRENT_LAST_NAME = CURRENT_LAST_NAME;
        this.CURRENT_MIDDLE_NAME = CURRENT_MIDDLE_NAME;
        this.CURRENT_FIRST_NAME = CURRENT_FIRST_NAME;
    }

    public int getPAPER_ID() {
        return PAPER_ID;
    }

    public void setPAPER_ID(int PAPER_ID) {
        this.PAPER_ID = PAPER_ID;
    }

    public String getPAPER_NUMBER_OR_CODE() {
        return PAPER_NUMBER_OR_CODE;
    }

    public void setPAPER_NUMBER_OR_CODE(String PAPER_NUMBER_OR_CODE) {
        this.PAPER_NUMBER_OR_CODE = PAPER_NUMBER_OR_CODE;
    }

    public String getPAPER_ABSTRACT_TITLE_1() {
        return PAPER_ABSTRACT_TITLE_1;
    }

    public void setPAPER_ABSTRACT_TITLE_1(String PAPER_ABSTRACT_TITLE_1) {
        this.PAPER_ABSTRACT_TITLE_1 = PAPER_ABSTRACT_TITLE_1;
    }

    public String getPAPER_ABSTRACT_TITLE_EN_1() {
        return PAPER_ABSTRACT_TITLE_EN_1;
    }

    public void setPAPER_ABSTRACT_TITLE_EN_1(String PAPER_ABSTRACT_TITLE_EN_1) {
        this.PAPER_ABSTRACT_TITLE_EN_1 = PAPER_ABSTRACT_TITLE_EN_1;
    }

    public int getCONFERENCE_SESSION_TOPIC_ID_1() {
        return CONFERENCE_SESSION_TOPIC_ID_1;
    }

    public void setCONFERENCE_SESSION_TOPIC_ID_1(int CONFERENCE_SESSION_TOPIC_ID_1) {
        this.CONFERENCE_SESSION_TOPIC_ID_1 = CONFERENCE_SESSION_TOPIC_ID_1;
    }

    public String getCONFERENCE_SESSION_TOPIC_NAME_1() {
        return CONFERENCE_SESSION_TOPIC_NAME_1;
    }

    public void setCONFERENCE_SESSION_TOPIC_NAME_1(String CONFERENCE_SESSION_TOPIC_NAME_1) {
        this.CONFERENCE_SESSION_TOPIC_NAME_1 = CONFERENCE_SESSION_TOPIC_NAME_1;
    }

    public String getCONFERENCE_SESSION_TOPIC_NAME_EN_1() {
        return CONFERENCE_SESSION_TOPIC_NAME_EN_1;
    }

    public void setCONFERENCE_SESSION_TOPIC_NAME_EN_1(String CONFERENCE_SESSION_TOPIC_NAME_EN_1) {
        this.CONFERENCE_SESSION_TOPIC_NAME_EN_1 = CONFERENCE_SESSION_TOPIC_NAME_EN_1;
    }

    public String getPAPER_ABSTRACT_TEXT_1() {
        return PAPER_ABSTRACT_TEXT_1;
    }

    public void setPAPER_ABSTRACT_TEXT_1(String PAPER_ABSTRACT_TEXT_1) {
        this.PAPER_ABSTRACT_TEXT_1 = PAPER_ABSTRACT_TEXT_1;
    }

    public String getPAPER_ABSTRACT_TEXT_EN_1() {
        return PAPER_ABSTRACT_TEXT_EN_1;
    }

    public void setPAPER_ABSTRACT_TEXT_EN_1(String PAPER_ABSTRACT_TEXT_EN_1) {
        this.PAPER_ABSTRACT_TEXT_EN_1 = PAPER_ABSTRACT_TEXT_EN_1;
    }

    public String getPAPER_ABSTRACT_ATTACHED_FILENAME_1() {
        return PAPER_ABSTRACT_ATTACHED_FILENAME_1;
    }

    public void setPAPER_ABSTRACT_ATTACHED_FILENAME_1(String PAPER_ABSTRACT_ATTACHED_FILENAME_1) {
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_1 = PAPER_ABSTRACT_ATTACHED_FILENAME_1;
    }

    public String getWORD_COUNT_OF_PAPER_ABSTRACT_1() {
        return WORD_COUNT_OF_PAPER_ABSTRACT_1;
    }

    public void setWORD_COUNT_OF_PAPER_ABSTRACT_1(String WORD_COUNT_OF_PAPER_ABSTRACT_1) {
        this.WORD_COUNT_OF_PAPER_ABSTRACT_1 = WORD_COUNT_OF_PAPER_ABSTRACT_1;
    }

    public String getKEYWORDS_1() {
        return KEYWORDS_1;
    }

    public void setKEYWORDS_1(String KEYWORDS_1) {
        this.KEYWORDS_1 = KEYWORDS_1;
    }

    public String getFULL_PAPER_OR_WORK_IN_PROGRESS_1() {
        return FULL_PAPER_OR_WORK_IN_PROGRESS_1;
    }

    public void setFULL_PAPER_OR_WORK_IN_PROGRESS_1(String FULL_PAPER_OR_WORK_IN_PROGRESS_1) {
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_1 = FULL_PAPER_OR_WORK_IN_PROGRESS_1;
    }

    public String getTYPE_OF_STUDY_ID_1() {
        return TYPE_OF_STUDY_ID_1;
    }

    public void setTYPE_OF_STUDY_ID_1(String TYPE_OF_STUDY_ID_1) {
        this.TYPE_OF_STUDY_ID_1 = TYPE_OF_STUDY_ID_1;
    }

    public String getTYPE_OF_STUDY_NAME_1() {
        return TYPE_OF_STUDY_NAME_1;
    }

    public void setTYPE_OF_STUDY_NAME_1(String TYPE_OF_STUDY_NAME_1) {
        this.TYPE_OF_STUDY_NAME_1 = TYPE_OF_STUDY_NAME_1;
    }

    public String getTYPE_OF_STUDY_NAME_EN_1() {
        return TYPE_OF_STUDY_NAME_EN_1;
    }

    public void setTYPE_OF_STUDY_NAME_EN_1(String TYPE_OF_STUDY_NAME_EN_1) {
        this.TYPE_OF_STUDY_NAME_EN_1 = TYPE_OF_STUDY_NAME_EN_1;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_ID_1() {
        return CONFERENCE_PRESENTATION_TYPE_ID_1;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID_1(String CONFERENCE_PRESENTATION_TYPE_ID_1) {
        this.CONFERENCE_PRESENTATION_TYPE_ID_1 = CONFERENCE_PRESENTATION_TYPE_ID_1;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_1() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_1;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_1(String CONFERENCE_PRESENTATION_TYPE_NAME_1) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_1 = CONFERENCE_PRESENTATION_TYPE_NAME_1;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN_1() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN_1;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN_1(String CONFERENCE_PRESENTATION_TYPE_NAME_EN_1) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_1 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_1;
    }

    public String getFIRST_SUBMITTED_DATE_1() {
        return FIRST_SUBMITTED_DATE_1;
    }

    public void setFIRST_SUBMITTED_DATE_1(String FIRST_SUBMITTED_DATE_1) {
        this.FIRST_SUBMITTED_DATE_1 = FIRST_SUBMITTED_DATE_1;
    }

    public String getLAST_REVISED_DATE_1() {
        return LAST_REVISED_DATE_1;
    }

    public void setLAST_REVISED_DATE_1(String LAST_REVISED_DATE_1) {
        this.LAST_REVISED_DATE_1 = LAST_REVISED_DATE_1;
    }

    public String getPAPER_ABSTRACT_TITLE_2() {
        return PAPER_ABSTRACT_TITLE_2;
    }

    public void setPAPER_ABSTRACT_TITLE_2(String PAPER_ABSTRACT_TITLE_2) {
        this.PAPER_ABSTRACT_TITLE_2 = PAPER_ABSTRACT_TITLE_2;
    }

    public String getPAPER_ABSTRACT_TITLE_EN_2() {
        return PAPER_ABSTRACT_TITLE_EN_2;
    }

    public void setPAPER_ABSTRACT_TITLE_EN_2(String PAPER_ABSTRACT_TITLE_EN_2) {
        this.PAPER_ABSTRACT_TITLE_EN_2 = PAPER_ABSTRACT_TITLE_EN_2;
    }

    public String getCONFERENCE_SESSION_TOPIC_ID_2() {
        return CONFERENCE_SESSION_TOPIC_ID_2;
    }

    public void setCONFERENCE_SESSION_TOPIC_ID_2(String CONFERENCE_SESSION_TOPIC_ID_2) {
        this.CONFERENCE_SESSION_TOPIC_ID_2 = CONFERENCE_SESSION_TOPIC_ID_2;
    }

    public String getCONFERENCE_SESSION_TOPIC_NAME_2() {
        return CONFERENCE_SESSION_TOPIC_NAME_2;
    }

    public void setCONFERENCE_SESSION_TOPIC_NAME_2(String CONFERENCE_SESSION_TOPIC_NAME_2) {
        this.CONFERENCE_SESSION_TOPIC_NAME_2 = CONFERENCE_SESSION_TOPIC_NAME_2;
    }

    public String getCONFERENCE_SESSION_TOPIC_NAME_EN_2() {
        return CONFERENCE_SESSION_TOPIC_NAME_EN_2;
    }

    public void setCONFERENCE_SESSION_TOPIC_NAME_EN_2(String CONFERENCE_SESSION_TOPIC_NAME_EN_2) {
        this.CONFERENCE_SESSION_TOPIC_NAME_EN_2 = CONFERENCE_SESSION_TOPIC_NAME_EN_2;
    }

    public String getPAPER_ABSTRACT_TEXT_2() {
        return PAPER_ABSTRACT_TEXT_2;
    }

    public void setPAPER_ABSTRACT_TEXT_2(String PAPER_ABSTRACT_TEXT_2) {
        this.PAPER_ABSTRACT_TEXT_2 = PAPER_ABSTRACT_TEXT_2;
    }

    public String getPAPER_ABSTRACT_TEXT_EN_2() {
        return PAPER_ABSTRACT_TEXT_EN_2;
    }

    public void setPAPER_ABSTRACT_TEXT_EN_2(String PAPER_ABSTRACT_TEXT_EN_2) {
        this.PAPER_ABSTRACT_TEXT_EN_2 = PAPER_ABSTRACT_TEXT_EN_2;
    }

    public String getPAPER_ABSTRACT_ATTACHED_FILENAME_2() {
        return PAPER_ABSTRACT_ATTACHED_FILENAME_2;
    }

    public void setPAPER_ABSTRACT_ATTACHED_FILENAME_2(String PAPER_ABSTRACT_ATTACHED_FILENAME_2) {
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_2 = PAPER_ABSTRACT_ATTACHED_FILENAME_2;
    }

    public String getWORD_COUNT_OF_PAPER_ABSTRACT_2() {
        return WORD_COUNT_OF_PAPER_ABSTRACT_2;
    }

    public void setWORD_COUNT_OF_PAPER_ABSTRACT_2(String WORD_COUNT_OF_PAPER_ABSTRACT_2) {
        this.WORD_COUNT_OF_PAPER_ABSTRACT_2 = WORD_COUNT_OF_PAPER_ABSTRACT_2;
    }

    public String getKEYWORDS_2() {
        return KEYWORDS_2;
    }

    public void setKEYWORDS_2(String KEYWORDS_2) {
        this.KEYWORDS_2 = KEYWORDS_2;
    }

    public String getFULL_PAPER_OR_WORK_IN_PROGRESS_2() {
        return FULL_PAPER_OR_WORK_IN_PROGRESS_2;
    }

    public void setFULL_PAPER_OR_WORK_IN_PROGRESS_2(String FULL_PAPER_OR_WORK_IN_PROGRESS_2) {
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_2 = FULL_PAPER_OR_WORK_IN_PROGRESS_2;
    }

    public String getTYPE_OF_STUDY_ID_2() {
        return TYPE_OF_STUDY_ID_2;
    }

    public void setTYPE_OF_STUDY_ID_2(String TYPE_OF_STUDY_ID_2) {
        this.TYPE_OF_STUDY_ID_2 = TYPE_OF_STUDY_ID_2;
    }

    public String getTYPE_OF_STUDY_NAME_2() {
        return TYPE_OF_STUDY_NAME_2;
    }

    public void setTYPE_OF_STUDY_NAME_2(String TYPE_OF_STUDY_NAME_2) {
        this.TYPE_OF_STUDY_NAME_2 = TYPE_OF_STUDY_NAME_2;
    }

    public String getTYPE_OF_STUDY_NAME_EN_2() {
        return TYPE_OF_STUDY_NAME_EN_2;
    }

    public void setTYPE_OF_STUDY_NAME_EN_2(String TYPE_OF_STUDY_NAME_EN_2) {
        this.TYPE_OF_STUDY_NAME_EN_2 = TYPE_OF_STUDY_NAME_EN_2;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_ID_2() {
        return CONFERENCE_PRESENTATION_TYPE_ID_2;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID_2(String CONFERENCE_PRESENTATION_TYPE_ID_2) {
        this.CONFERENCE_PRESENTATION_TYPE_ID_2 = CONFERENCE_PRESENTATION_TYPE_ID_2;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_2() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_2;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_2(String CONFERENCE_PRESENTATION_TYPE_NAME_2) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_2 = CONFERENCE_PRESENTATION_TYPE_NAME_2;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN_2() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN_2;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN_2(String CONFERENCE_PRESENTATION_TYPE_NAME_EN_2) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_2 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_2;
    }

    public String getFIRST_SUBMITTED_DATE_2() {
        return FIRST_SUBMITTED_DATE_2;
    }

    public void setFIRST_SUBMITTED_DATE_2(String FIRST_SUBMITTED_DATE_2) {
        this.FIRST_SUBMITTED_DATE_2 = FIRST_SUBMITTED_DATE_2;
    }

    public String getLAST_REVISED_DATE_2() {
        return LAST_REVISED_DATE_2;
    }

    public void setLAST_REVISED_DATE_2(String LAST_REVISED_DATE_2) {
        this.LAST_REVISED_DATE_2 = LAST_REVISED_DATE_2;
    }

    public String getLAST_REVISED_DATE_3() {
        return LAST_REVISED_DATE_3;
    }

    public void setLAST_REVISED_DATE_3(String LAST_REVISED_DATE_3) {
        this.LAST_REVISED_DATE_3 = LAST_REVISED_DATE_3;
    }

    public String getPAPER_ABSTRACT_TEXT_3() {
        return PAPER_ABSTRACT_TEXT_3;
    }

    public void setPAPER_ABSTRACT_TEXT_3(String PAPER_ABSTRACT_TEXT_3) {
        this.PAPER_ABSTRACT_TEXT_3 = PAPER_ABSTRACT_TEXT_3;
    }

    public String getPAPER_ABSTRACT_TEXT_EN_3() {
        return PAPER_ABSTRACT_TEXT_EN_3;
    }

    public void setPAPER_ABSTRACT_TEXT_EN_3(String PAPER_ABSTRACT_TEXT_EN_3) {
        this.PAPER_ABSTRACT_TEXT_EN_3 = PAPER_ABSTRACT_TEXT_EN_3;
    }

    public String getPAPER_ABSTRACT_ATTACHED_FILENAME_3() {
        return PAPER_ABSTRACT_ATTACHED_FILENAME_3;
    }

    public void setPAPER_ABSTRACT_ATTACHED_FILENAME_3(String PAPER_ABSTRACT_ATTACHED_FILENAME_3) {
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_3 = PAPER_ABSTRACT_ATTACHED_FILENAME_3;
    }

    public String getWORD_COUNT_OF_PAPER_ABSTRACT_3() {
        return WORD_COUNT_OF_PAPER_ABSTRACT_3;
    }

    public void setWORD_COUNT_OF_PAPER_ABSTRACT_3(String WORD_COUNT_OF_PAPER_ABSTRACT_3) {
        this.WORD_COUNT_OF_PAPER_ABSTRACT_3 = WORD_COUNT_OF_PAPER_ABSTRACT_3;
    }

    public String getKEYWORDS_3() {
        return KEYWORDS_3;
    }

    public void setKEYWORDS_3(String KEYWORDS_3) {
        this.KEYWORDS_3 = KEYWORDS_3;
    }

    public String getFULL_PAPER_OR_WORK_IN_PROGRESS_3() {
        return FULL_PAPER_OR_WORK_IN_PROGRESS_3;
    }

    public void setFULL_PAPER_OR_WORK_IN_PROGRESS_3(String FULL_PAPER_OR_WORK_IN_PROGRESS_3) {
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_3 = FULL_PAPER_OR_WORK_IN_PROGRESS_3;
    }

    public String getTYPE_OF_STUDY_ID_3() {
        return TYPE_OF_STUDY_ID_3;
    }

    public void setTYPE_OF_STUDY_ID_3(String TYPE_OF_STUDY_ID_3) {
        this.TYPE_OF_STUDY_ID_3 = TYPE_OF_STUDY_ID_3;
    }

    public String getTYPE_OF_STUDY_NAME_3() {
        return TYPE_OF_STUDY_NAME_3;
    }

    public void setTYPE_OF_STUDY_NAME_3(String TYPE_OF_STUDY_NAME_3) {
        this.TYPE_OF_STUDY_NAME_3 = TYPE_OF_STUDY_NAME_3;
    }

    public String getTYPE_OF_STUDY_NAME_EN_3() {
        return TYPE_OF_STUDY_NAME_EN_3;
    }

    public void setTYPE_OF_STUDY_NAME_EN_3(String TYPE_OF_STUDY_NAME_EN_3) {
        this.TYPE_OF_STUDY_NAME_EN_3 = TYPE_OF_STUDY_NAME_EN_3;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_ID_3() {
        return CONFERENCE_PRESENTATION_TYPE_ID_3;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID_3(String CONFERENCE_PRESENTATION_TYPE_ID_3) {
        this.CONFERENCE_PRESENTATION_TYPE_ID_3 = CONFERENCE_PRESENTATION_TYPE_ID_3;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_3() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_3;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_3(String CONFERENCE_PRESENTATION_TYPE_NAME_3) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_3 = CONFERENCE_PRESENTATION_TYPE_NAME_3;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN_3() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN_3;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN_3(String CONFERENCE_PRESENTATION_TYPE_NAME_EN_3) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_3 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_3;
    }

    public String getFIRST_SUBMITTED_DATE_3() {
        return FIRST_SUBMITTED_DATE_3;
    }

    public void setFIRST_SUBMITTED_DATE_3(String FIRST_SUBMITTED_DATE_3) {
        this.FIRST_SUBMITTED_DATE_3 = FIRST_SUBMITTED_DATE_3;
    }

    public String getLAST_REVISED_DATE_4() {
        return LAST_REVISED_DATE_4;
    }

    public void setLAST_REVISED_DATE_4(String LAST_REVISED_DATE_4) {
        this.LAST_REVISED_DATE_4 = LAST_REVISED_DATE_4;
    }

    public String getPAPER_ABSTRACT_TEXT_4() {
        return PAPER_ABSTRACT_TEXT_4;
    }

    public void setPAPER_ABSTRACT_TEXT_4(String PAPER_ABSTRACT_TEXT_4) {
        this.PAPER_ABSTRACT_TEXT_4 = PAPER_ABSTRACT_TEXT_4;
    }

    public String getPAPER_ABSTRACT_TEXT_EN_4() {
        return PAPER_ABSTRACT_TEXT_EN_4;
    }

    public void setPAPER_ABSTRACT_TEXT_EN_4(String PAPER_ABSTRACT_TEXT_EN_4) {
        this.PAPER_ABSTRACT_TEXT_EN_4 = PAPER_ABSTRACT_TEXT_EN_4;
    }

    public String getPAPER_ABSTRACT_ATTACHED_FILENAME_4() {
        return PAPER_ABSTRACT_ATTACHED_FILENAME_4;
    }

    public void setPAPER_ABSTRACT_ATTACHED_FILENAME_4(String PAPER_ABSTRACT_ATTACHED_FILENAME_4) {
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_4 = PAPER_ABSTRACT_ATTACHED_FILENAME_4;
    }

    public String getWORD_COUNT_OF_PAPER_ABSTRACT_4() {
        return WORD_COUNT_OF_PAPER_ABSTRACT_4;
    }

    public void setWORD_COUNT_OF_PAPER_ABSTRACT_4(String WORD_COUNT_OF_PAPER_ABSTRACT_4) {
        this.WORD_COUNT_OF_PAPER_ABSTRACT_4 = WORD_COUNT_OF_PAPER_ABSTRACT_4;
    }

    public String getKEYWORDS_4() {
        return KEYWORDS_4;
    }

    public void setKEYWORDS_4(String KEYWORDS_4) {
        this.KEYWORDS_4 = KEYWORDS_4;
    }

    public String getFULL_PAPER_OR_WORK_IN_PROGRESS_4() {
        return FULL_PAPER_OR_WORK_IN_PROGRESS_4;
    }

    public void setFULL_PAPER_OR_WORK_IN_PROGRESS_4(String FULL_PAPER_OR_WORK_IN_PROGRESS_4) {
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_4 = FULL_PAPER_OR_WORK_IN_PROGRESS_4;
    }

    public String getTYPE_OF_STUDY_ID_4() {
        return TYPE_OF_STUDY_ID_4;
    }

    public void setTYPE_OF_STUDY_ID_4(String TYPE_OF_STUDY_ID_4) {
        this.TYPE_OF_STUDY_ID_4 = TYPE_OF_STUDY_ID_4;
    }

    public String getTYPE_OF_STUDY_NAME_4() {
        return TYPE_OF_STUDY_NAME_4;
    }

    public void setTYPE_OF_STUDY_NAME_4(String TYPE_OF_STUDY_NAME_4) {
        this.TYPE_OF_STUDY_NAME_4 = TYPE_OF_STUDY_NAME_4;
    }

    public String getTYPE_OF_STUDY_NAME_EN_4() {
        return TYPE_OF_STUDY_NAME_EN_4;
    }

    public void setTYPE_OF_STUDY_NAME_EN_4(String TYPE_OF_STUDY_NAME_EN_4) {
        this.TYPE_OF_STUDY_NAME_EN_4 = TYPE_OF_STUDY_NAME_EN_4;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_ID_4() {
        return CONFERENCE_PRESENTATION_TYPE_ID_4;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID_4(String CONFERENCE_PRESENTATION_TYPE_ID_4) {
        this.CONFERENCE_PRESENTATION_TYPE_ID_4 = CONFERENCE_PRESENTATION_TYPE_ID_4;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_4() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_4;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_4(String CONFERENCE_PRESENTATION_TYPE_NAME_4) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_4 = CONFERENCE_PRESENTATION_TYPE_NAME_4;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN_4() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN_4;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN_4(String CONFERENCE_PRESENTATION_TYPE_NAME_EN_4) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_4 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_4;
    }

    public String getFIRST_SUBMITTED_DATE_4() {
        return FIRST_SUBMITTED_DATE_4;
    }

    public void setFIRST_SUBMITTED_DATE_4(String FIRST_SUBMITTED_DATE_4) {
        this.FIRST_SUBMITTED_DATE_4 = FIRST_SUBMITTED_DATE_4;
    }

    public String getLAST_REVISED_DATE_5() {
        return LAST_REVISED_DATE_5;
    }

    public void setLAST_REVISED_DATE_5(String LAST_REVISED_DATE_5) {
        this.LAST_REVISED_DATE_5 = LAST_REVISED_DATE_5;
    }

    public String getPAPER_ABSTRACT_TEXT_5() {
        return PAPER_ABSTRACT_TEXT_5;
    }

    public void setPAPER_ABSTRACT_TEXT_5(String PAPER_ABSTRACT_TEXT_5) {
        this.PAPER_ABSTRACT_TEXT_5 = PAPER_ABSTRACT_TEXT_5;
    }

    public String getPAPER_ABSTRACT_TEXT_EN_5() {
        return PAPER_ABSTRACT_TEXT_EN_5;
    }

    public void setPAPER_ABSTRACT_TEXT_EN_5(String PAPER_ABSTRACT_TEXT_EN_5) {
        this.PAPER_ABSTRACT_TEXT_EN_5 = PAPER_ABSTRACT_TEXT_EN_5;
    }

    public String getPAPER_ABSTRACT_ATTACHED_FILENAME_5() {
        return PAPER_ABSTRACT_ATTACHED_FILENAME_5;
    }

    public void setPAPER_ABSTRACT_ATTACHED_FILENAME_5(String PAPER_ABSTRACT_ATTACHED_FILENAME_5) {
        this.PAPER_ABSTRACT_ATTACHED_FILENAME_5 = PAPER_ABSTRACT_ATTACHED_FILENAME_5;
    }

    public String getWORD_COUNT_OF_PAPER_ABSTRACT_5() {
        return WORD_COUNT_OF_PAPER_ABSTRACT_5;
    }

    public void setWORD_COUNT_OF_PAPER_ABSTRACT_5(String WORD_COUNT_OF_PAPER_ABSTRACT_5) {
        this.WORD_COUNT_OF_PAPER_ABSTRACT_5 = WORD_COUNT_OF_PAPER_ABSTRACT_5;
    }

    public String getKEYWORDS_5() {
        return KEYWORDS_5;
    }

    public void setKEYWORDS_5(String KEYWORDS_5) {
        this.KEYWORDS_5 = KEYWORDS_5;
    }

    public String getFULL_PAPER_OR_WORK_IN_PROGRESS_5() {
        return FULL_PAPER_OR_WORK_IN_PROGRESS_5;
    }

    public void setFULL_PAPER_OR_WORK_IN_PROGRESS_5(String FULL_PAPER_OR_WORK_IN_PROGRESS_5) {
        this.FULL_PAPER_OR_WORK_IN_PROGRESS_5 = FULL_PAPER_OR_WORK_IN_PROGRESS_5;
    }

    public String getTYPE_OF_STUDY_ID_5() {
        return TYPE_OF_STUDY_ID_5;
    }

    public void setTYPE_OF_STUDY_ID_5(String TYPE_OF_STUDY_ID_5) {
        this.TYPE_OF_STUDY_ID_5 = TYPE_OF_STUDY_ID_5;
    }

    public String getTYPE_OF_STUDY_NAME_5() {
        return TYPE_OF_STUDY_NAME_5;
    }

    public void setTYPE_OF_STUDY_NAME_5(String TYPE_OF_STUDY_NAME_5) {
        this.TYPE_OF_STUDY_NAME_5 = TYPE_OF_STUDY_NAME_5;
    }

    public String getTYPE_OF_STUDY_NAME_EN_5() {
        return TYPE_OF_STUDY_NAME_EN_5;
    }

    public void setTYPE_OF_STUDY_NAME_EN_5(String TYPE_OF_STUDY_NAME_EN_5) {
        this.TYPE_OF_STUDY_NAME_EN_5 = TYPE_OF_STUDY_NAME_EN_5;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_ID_5() {
        return CONFERENCE_PRESENTATION_TYPE_ID_5;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID_5(String CONFERENCE_PRESENTATION_TYPE_ID_5) {
        this.CONFERENCE_PRESENTATION_TYPE_ID_5 = CONFERENCE_PRESENTATION_TYPE_ID_5;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_5() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_5;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_5(String CONFERENCE_PRESENTATION_TYPE_NAME_5) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_5 = CONFERENCE_PRESENTATION_TYPE_NAME_5;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN_5() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN_5;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN_5(String CONFERENCE_PRESENTATION_TYPE_NAME_EN_5) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN_5 = CONFERENCE_PRESENTATION_TYPE_NAME_EN_5;
    }

    public String getFIRST_SUBMITTED_DATE_5() {
        return FIRST_SUBMITTED_DATE_5;
    }

    public void setFIRST_SUBMITTED_DATE_5(String FIRST_SUBMITTED_DATE_5) {
        this.FIRST_SUBMITTED_DATE_5 = FIRST_SUBMITTED_DATE_5;
    }

    public String getPAPER_ABSTRACT_WITHDRAWN() {
        return PAPER_ABSTRACT_WITHDRAWN;
    }

    public void setPAPER_ABSTRACT_WITHDRAWN(String PAPER_ABSTRACT_WITHDRAWN) {
        this.PAPER_ABSTRACT_WITHDRAWN = PAPER_ABSTRACT_WITHDRAWN;
    }

    public String getPAPER_ABSTRACT_WITHDRAWN_SCRIPT() {
        return PAPER_ABSTRACT_WITHDRAWN_SCRIPT;
    }

    public void setPAPER_ABSTRACT_WITHDRAWN_SCRIPT(String PAPER_ABSTRACT_WITHDRAWN_SCRIPT) {
        this.PAPER_ABSTRACT_WITHDRAWN_SCRIPT = PAPER_ABSTRACT_WITHDRAWN_SCRIPT;
    }

    public String getPAPER_ABSTRACT_WITHDRAWN_DATE() {
        return PAPER_ABSTRACT_WITHDRAWN_DATE;
    }

    public void setPAPER_ABSTRACT_WITHDRAWN_DATE(String PAPER_ABSTRACT_WITHDRAWN_DATE) {
        this.PAPER_ABSTRACT_WITHDRAWN_DATE = PAPER_ABSTRACT_WITHDRAWN_DATE;
    }

    public String getPAPER_ABSTRACT_WITHDRAWN_NOTE() {
        return PAPER_ABSTRACT_WITHDRAWN_NOTE;
    }

    public void setPAPER_ABSTRACT_WITHDRAWN_NOTE(String PAPER_ABSTRACT_WITHDRAWN_NOTE) {
        this.PAPER_ABSTRACT_WITHDRAWN_NOTE = PAPER_ABSTRACT_WITHDRAWN_NOTE;
    }

    public String getFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT() {
        return FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT;
    }

    public void setFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT(String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT) {
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT;
    }

    public String getFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT() {
        return FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT;
    }

    public void setFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT(String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT) {
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_SCRIPT;
    }

    public String getFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE() {
        return FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE;
    }

    public void setFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE(String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE) {
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_DATE;
    }

    public String getFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID() {
        return FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID;
    }

    public void setFINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID(String FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID) {
        this.FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID = FINAL_APPROVAL_OR_REJECTION_OF_PAPER_ABSTRACT_REVIEWER_PERSON_ID;
    }

    public int getASSIGNED_CONFERENCE_SESSION_TOPIC_ID() {
        return ASSIGNED_CONFERENCE_SESSION_TOPIC_ID;
    }

    public void setASSIGNED_CONFERENCE_SESSION_TOPIC_ID(int ASSIGNED_CONFERENCE_SESSION_TOPIC_ID) {
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_ID = ASSIGNED_CONFERENCE_SESSION_TOPIC_ID;
    }

    public String getASSIGNED_CONFERENCE_SESSION_TOPIC_NAME() {
        return ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME;
    }

    public void setASSIGNED_CONFERENCE_SESSION_TOPIC_NAME(String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME) {
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME = ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME;
    }

    public String getASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN() {
        return ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN;
    }

    public void setASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN(String ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN) {
        this.ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN = ASSIGNED_CONFERENCE_SESSION_TOPIC_NAME_EN;
    }

    public int getPERSON_ID() {
        return PERSON_ID;
    }

    public void setPERSON_ID(int PERSON_ID) {
        this.PERSON_ID = PERSON_ID;
    }

    public String getCURRENT_LAST_NAME() {
        return CURRENT_LAST_NAME;
    }

    public void setCURRENT_LAST_NAME(String CURRENT_LAST_NAME) {
        this.CURRENT_LAST_NAME = CURRENT_LAST_NAME;
    }

    public String getCURRENT_MIDDLE_NAME() {
        return CURRENT_MIDDLE_NAME;
    }

    public void setCURRENT_MIDDLE_NAME(String CURRENT_MIDDLE_NAME) {
        this.CURRENT_MIDDLE_NAME = CURRENT_MIDDLE_NAME;
    }

    public String getCURRENT_FIRST_NAME() {
        return CURRENT_FIRST_NAME;
    }

    public void setCURRENT_FIRST_NAME(String CURRENT_FIRST_NAME) {
        this.CURRENT_FIRST_NAME = CURRENT_FIRST_NAME;
    }
}
