package cse.duytan.coms.models;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

/**
 * Created by lehoangdung on 8/29/2017.
 */

public class PresentationTypeModel implements Serializable {
    @SerializedName("CONFERENCE_PRESENTATION_TYPE_ID")
    public int CONFERENCE_PRESENTATION_TYPE_ID;

    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME")
    public String CONFERENCE_PRESENTATION_TYPE_NAME;

    @SerializedName("CONFERENCE_PRESENTATION_TYPE_NAME_EN")
    public String CONFERENCE_PRESENTATION_TYPE_NAME_EN;

    public PresentationTypeModel() {
    }

    public PresentationTypeModel(int CONFERENCE_PRESENTATION_TYPE_ID, String CONFERENCE_PRESENTATION_TYPE_NAME, String CONFERENCE_PRESENTATION_TYPE_NAME_EN) {
        this.CONFERENCE_PRESENTATION_TYPE_ID = CONFERENCE_PRESENTATION_TYPE_ID;
        this.CONFERENCE_PRESENTATION_TYPE_NAME = CONFERENCE_PRESENTATION_TYPE_NAME;
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN = CONFERENCE_PRESENTATION_TYPE_NAME_EN;
    }

    public int getCONFERENCE_PRESENTATION_TYPE_ID() {
        return CONFERENCE_PRESENTATION_TYPE_ID;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_ID(int CONFERENCE_PRESENTATION_TYPE_ID) {
        this.CONFERENCE_PRESENTATION_TYPE_ID = CONFERENCE_PRESENTATION_TYPE_ID;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME() {
        return CONFERENCE_PRESENTATION_TYPE_NAME;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME(String CONFERENCE_PRESENTATION_TYPE_NAME) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME = CONFERENCE_PRESENTATION_TYPE_NAME;
    }

    public String getCONFERENCE_PRESENTATION_TYPE_NAME_EN() {
        return CONFERENCE_PRESENTATION_TYPE_NAME_EN;
    }

    public void setCONFERENCE_PRESENTATION_TYPE_NAME_EN(String CONFERENCE_PRESENTATION_TYPE_NAME_EN) {
        this.CONFERENCE_PRESENTATION_TYPE_NAME_EN = CONFERENCE_PRESENTATION_TYPE_NAME_EN;
    }
}
